import type { Job, Certification, Resource } from "@/types";

export const jobs: Job[] = [
  {
    id: "1",
    title: "Software Engineer",
    company: "Microsoft",
    location: "Redmond, WA",
    salary: "$120,000 - $180,000",
    type: "Full-time",
    description: "Join our team building the future of cloud computing. Work on Azure services and collaborate with talented engineers.",
    requirements: ["3+ years experience", "TypeScript/JavaScript", "Cloud experience", "CS degree preferred"],
    posted: "2 days ago",
    remote: true,
  },
  {
    id: "2",
    title: "Data Scientist",
    company: "Amazon",
    location: "Seattle, WA",
    salary: "$140,000 - $200,000",
    type: "Full-time",
    description: "Use machine learning to solve complex business problems and improve customer experience at scale.",
    requirements: ["Python/R proficiency", "ML/AI experience", "SQL skills", "Statistics background"],
    posted: "1 week ago",
    remote: false,
  },
  {
    id: "3",
    title: "UX Designer",
    company: "Expedia",
    location: "Seattle, WA",
    salary: "$95,000 - $140,000",
    type: "Full-time",
    description: "Design beautiful, intuitive travel experiences for millions of users worldwide.",
    requirements: ["Figma expertise", "User research", "Prototyping skills", "Portfolio required"],
    posted: "3 days ago",
    remote: true,
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "Tableau",
    location: "Seattle, WA",
    salary: "$130,000 - $175,000",
    type: "Full-time",
    description: "Build and maintain our CI/CD pipelines and cloud infrastructure.",
    requirements: ["Kubernetes", "AWS/Azure", "Terraform", "Docker"],
    posted: "5 days ago",
    remote: true,
  },
  {
    id: "5",
    title: "Product Manager Intern",
    company: "Zillow",
    location: "Seattle, WA",
    salary: "$35/hour",
    type: "Internship",
    description: "Learn product management while working on real features for our home-buying platform.",
    requirements: ["Currently enrolled student", "Strong communication", "Analytical mindset", "Interest in real estate tech"],
    posted: "1 day ago",
    remote: false,
  },
  {
    id: "6",
    title: "Frontend Developer",
    company: "Starbucks",
    location: "Seattle, WA",
    salary: "$100,000 - $145,000",
    type: "Full-time",
    description: "Build the digital experiences that connect millions of coffee lovers with their favorite beverages.",
    requirements: ["React/Next.js", "TypeScript", "CSS/Tailwind", "Mobile-first design"],
    posted: "4 days ago",
    remote: true,
  },
  {
    id: "7",
    title: "Cybersecurity Analyst",
    company: "Boeing",
    location: "Everett, WA",
    salary: "$110,000 - $160,000",
    type: "Full-time",
    description: "Protect critical aerospace systems and ensure compliance with security standards.",
    requirements: ["Security certifications", "Network security", "Incident response", "Clearance eligible"],
    posted: "1 week ago",
    remote: false,
  },
  {
    id: "8",
    title: "Marketing Coordinator",
    company: "REI",
    location: "Kent, WA",
    salary: "$55,000 - $70,000",
    type: "Full-time",
    description: "Help share the outdoor adventure with our passionate community of members.",
    requirements: ["Marketing degree", "Social media", "Content creation", "Outdoor enthusiast"],
    posted: "2 days ago",
    remote: true,
  },
];

export const certifications: Certification[] = [
  {
    id: "1",
    name: "AWS Solutions Architect",
    provider: "Amazon Web Services",
    description: "Design distributed systems and deploy applications on AWS cloud infrastructure.",
    duration: "3-6 months",
    cost: "$300",
    level: "Intermediate",
    category: "Cloud Computing",
    url: "https://aws.amazon.com/certification/",
  },
  {
    id: "2",
    name: "Google Data Analytics",
    provider: "Google",
    description: "Learn data analysis, visualization, and SQL to make data-driven decisions.",
    duration: "6 months",
    cost: "Free (Coursera)",
    level: "Beginner",
    category: "Data Analytics",
    url: "https://grow.google/certificates/data-analytics/",
  },
  {
    id: "3",
    name: "PMP Certification",
    provider: "PMI",
    description: "Project Management Professional certification for leading and directing projects.",
    duration: "3-6 months",
    cost: "$555",
    level: "Advanced",
    category: "Project Management",
    url: "https://www.pmi.org/certifications/project-management-pmp",
  },
  {
    id: "4",
    name: "CompTIA Security+",
    provider: "CompTIA",
    description: "Foundation-level cybersecurity certification for IT professionals.",
    duration: "2-3 months",
    cost: "$392",
    level: "Beginner",
    category: "Cybersecurity",
    url: "https://www.comptia.org/certifications/security",
  },
  {
    id: "5",
    name: "Certified Scrum Master",
    provider: "Scrum Alliance",
    description: "Learn to facilitate Scrum teams and implement agile methodologies.",
    duration: "2 days + exam",
    cost: "$500-1000",
    level: "Beginner",
    category: "Agile",
    url: "https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster",
  },
  {
    id: "6",
    name: "Microsoft Azure Fundamentals",
    provider: "Microsoft",
    description: "Entry-level Azure cloud concepts and services certification.",
    duration: "1-2 months",
    cost: "$99",
    level: "Beginner",
    category: "Cloud Computing",
    url: "https://learn.microsoft.com/en-us/certifications/azure-fundamentals/",
  },
];

export const resources: Resource[] = [
  {
    id: "1",
    title: "WSU Career Services",
    description: "Official WSU career counseling, resume reviews, and job search assistance.",
    category: "Career Services",
    url: "https://ascc.wsu.edu/career-services/",
    type: "Tool",
  },
  {
    id: "2",
    title: "Tech Interview Handbook",
    description: "Comprehensive guide for technical interview preparation.",
    category: "Interview Prep",
    url: "https://www.techinterviewhandbook.org/",
    type: "Article",
  },
  {
    id: "3",
    title: "Resume Worded",
    description: "AI-powered resume and LinkedIn optimization tool.",
    category: "Resume",
    url: "https://resumeworded.com/",
    type: "Tool",
  },
  {
    id: "4",
    title: "Levels.fyi",
    description: "Compare compensation across tech companies and levels.",
    category: "Salary",
    url: "https://www.levels.fyi/",
    type: "Tool",
  },
  {
    id: "5",
    title: "Handshake",
    description: "Job platform specifically for college students and recent grads.",
    category: "Job Search",
    url: "https://joinhandshake.com/",
    type: "Tool",
  },
  {
    id: "6",
    title: "LeetCode",
    description: "Practice coding problems for technical interviews.",
    category: "Interview Prep",
    url: "https://leetcode.com/",
    type: "Tool",
  },
];

export const professions = [
  "Software Engineering",
  "Data Science",
  "Product Management",
  "UX Design",
  "Marketing",
  "Finance",
  "Healthcare",
  "Education",
  "Business Administration",
  "Cybersecurity",
];
